disabled_rules:
  - trailing_whitespace
  - line_length
opt_in_rules:
  - empty_count
  - force_unwrapping
included:
  - Projects
  - Shared
excluded:
  - Tools/Automation/_merge_backups
  - Tools/Imported
  - *.generated.swift
