#!/bin/bash

# CodingReviewer Project Configuration
# This file contains project-specific settings for automation and MCP workflows

# Project Information
PROJECT_NAME="CodingReviewer"
PROJECT_TYPE="macOS_SwiftUI"
PROJECT_LANGUAGE="Swift"
PROJECT_FRAMEWORK="SwiftUI"

# Build Configuration
BUILD_SCHEME="CodingReviewer"
BUILD_CONFIGURATION="Debug"
TARGET_DEVICE="Mac"
TARGET_OS="macOS 15.0"

# Source Directories
SOURCE_DIR="."
TESTS_DIR="CodingReviewerTests"
UI_TESTS_DIR="CodingReviewerUITests"

# Automation Settings
ENABLE_AUTO_BUILD=true
ENABLE_AUTO_TEST=true
ENABLE_AUTO_LINT=true
ENABLE_AUTO_FORMAT=true
ENABLE_MCP_INTEGRATION=true
ENABLE_AI_ENHANCEMENT=true

# MCP Workflow Configuration
MCP_GITHUB_INTEGRATION=true
MCP_AUTO_PR=true
MCP_AUTO_REVIEW=true
MCP_NOTIFICATION_LEVEL="all"

# AI Enhancement Settings
AI_CODE_ANALYSIS=true
AI_PATTERN_RECOGNITION=true
AI_AUTOMATED_FIXES=true
AI_DOCUMENTATION_GENERATION=true

# Notification Settings
SLACK_NOTIFICATIONS=false
EMAIL_NOTIFICATIONS=false
GITHUB_NOTIFICATIONS=true

# Quality Gates
MIN_COVERAGE_THRESHOLD=80
MAX_BUILD_TIME_MINUTES=10
MAX_TEST_TIME_MINUTES=5

# File Patterns
SWIFT_FILES="**/*.swift"
EXCLUDED_PATTERNS="**/Build/**,**/DerivedData/**,**/*.xcworkspace/**"

# Export Configuration
export PROJECT_NAME BUILD_SCHEME BUILD_CONFIGURATION TARGET_DEVICE TARGET_OS
export SOURCE_DIR TESTS_DIR UI_TESTS_DIR
export ENABLE_AUTO_BUILD ENABLE_AUTO_TEST ENABLE_AUTO_LINT ENABLE_AUTO_FORMAT
export ENABLE_MCP_INTEGRATION ENABLE_AI_ENHANCEMENT
export MCP_GITHUB_INTEGRATION MCP_AUTO_PR MCP_AUTO_REVIEW MCP_NOTIFICATION_LEVEL
export AI_CODE_ANALYSIS AI_PATTERN_RECOGNITION AI_AUTOMATED_FIXES AI_DOCUMENTATION_GENERATION
export MIN_COVERAGE_THRESHOLD MAX_BUILD_TIME_MINUTES MAX_TEST_TIME_MINUTES
export SWIFT_FILES EXCLUDED_PATTERNS

echo "✅ CodingReviewer project configuration loaded (macOS Code Review App)"
