#!/bin/bash

# Environment Provisioning Script
# Generated by Advanced CI/CD Enhancement System

echo "🌍 Environment Provisioning System v1.0"
echo "========================================"

ENVIRONMENT="${1:-staging}"
ACTION="${2:-plan}"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Validate inputs
if [[ ! "$ENVIRONMENT" =~ ^(development|staging|production)$ ]]; then
    echo -e "${RED}❌ Invalid environment: $ENVIRONMENT${NC}"
    echo "Valid environments: development, staging, production"
    exit 1
fi

if [[ ! "$ACTION" =~ ^(plan|apply|destroy)$ ]]; then
    echo -e "${RED}❌ Invalid action: $ACTION${NC}"
    echo "Valid actions: plan, apply, destroy"
    exit 1
fi

echo -e "${YELLOW}🚀 Starting $ACTION for $ENVIRONMENT environment${NC}"

# Initialize Terraform
echo "📦 Initializing Terraform..."
terraform init

# Select or create workspace
echo "🏗️ Selecting workspace: $ENVIRONMENT"
terraform workspace select "$ENVIRONMENT" || terraform workspace new "$ENVIRONMENT"

# Execute action
case "$ACTION" in
    "plan")
        echo "📋 Creating execution plan..."
        terraform plan -var="environment=$ENVIRONMENT" -out="$ENVIRONMENT.tfplan"
        ;;
    "apply")
        echo "🔧 Applying infrastructure changes..."
        if [ -f "$ENVIRONMENT.tfplan" ]; then
            terraform apply "$ENVIRONMENT.tfplan"
        else
            terraform apply -var="environment=$ENVIRONMENT" -auto-approve
        fi
        ;;
    "destroy")
        echo -e "${RED}💥 Destroying infrastructure...${NC}"
        terraform destroy -var="environment=$ENVIRONMENT" -auto-approve
        ;;
esac

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ $ACTION completed successfully for $ENVIRONMENT${NC}"
else
    echo -e "${RED}❌ $ACTION failed for $ENVIRONMENT${NC}"
    exit 1
fi

# Post-provisioning tasks
if [ "$ACTION" = "apply" ]; then
    echo "📊 Gathering infrastructure information..."
    terraform output
    
    echo "🔍 Running infrastructure validation..."
    # Add validation checks here
    
    echo -e "${GREEN}🎉 Environment $ENVIRONMENT is ready!${NC}"
fi
